services:
  api:
    build: .
    container_name: askly_api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=5432;
        Database=AsklyDb;
        Username=postgres;
        Password=123
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: askly_postgres
    environment:
      POSTGRES_DB: AsklyDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  pgdata:
